# Generated by Django 5.0.14 on 2026-09-20 15:57

import common.images
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=64)),
                ('value', models.JSONField()),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_content', to='salons.salon')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'site_content',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='salons.salon')),
            ],
            options={
                'db_table': 'testimonial',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='salons.salon')),
            ],
            options={
                'db_table': 'faq_item',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['salon', 'is_published', 'display_order'], name='faq_item_salon_i_446fe4_idx')],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='gallery/', validators=[common.images.validate_image_file])),
                ('alt_text', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='salons.salon')),
            ],
            options={
                'db_table': 'gallery_image',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['salon', 'is_active', 'display_order'], name='gallery_ima_salon_i_95e5b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('refunds', 'Refund Policy'), ('promotion-rules', 'Promotion Rules')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body_markdown', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_pages', to='salons.salon')),
            ],
            options={
                'db_table': 'legal_page',
                'ordering': ['slug', '-version'],
                'indexes': [models.Index(fields=['salon', 'slug', '-version'], name='legal_page_salon_i_c6c2bc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='legalpage',
            constraint=models.UniqueConstraint(fields=('salon', 'slug', 'version'), name='uniq_legal_page_salon_slug_version'),
        ),
        migrations.AddConstraint(
            model_name='sitecontent',
            constraint=models.UniqueConstraint(fields=('salon', 'key'), name='uniq_site_content_salon_key'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['salon', 'is_published', 'display_order'], name='testimonial_salon_i_9635bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='testimonial',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='ck_testimonial_rating_1_5'),
        ),
    ]
