# Generated by Django 5.0.14 on 2026-09-21 01:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_order_number', models.CharField(max_length=20, unique=True)),
                ('subtotal_paise', models.BigIntegerField()),
                ('discount_paise', models.BigIntegerField(default=0)),
                ('total_paise', models.BigIntegerField()),
                ('discount_percent_applied', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_FAILED', 'Payment failed'), ('PAID', 'Paid'), ('LUCKY_DECIDED', 'Lucky result decided'), ('REFUND_PENDING', 'Refund pending'), ('REFUNDED', 'Refunded'), ('REFUND_FAILED', 'Refund failed'), ('COUPON_ACTIVE', 'Coupon active'), ('REDEEMED', 'Redeemed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24)),
                ('enters_lucky_campaign', models.BooleanField(default=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name_snapshot', models.CharField(max_length=200)),
                ('service_slug_snapshot', models.SlugField(max_length=200)),
                ('unit_price_paise', models.BigIntegerField()),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('line_total_paise', models.BigIntegerField()),
                ('discount_alloc_paise', models.BigIntegerField(default=0)),
                ('net_paid_paise', models.BigIntegerField()),
            ],
            options={
                'db_table': 'order_item',
                'ordering': ['created_at'],
            },
        ),
    ]
