# Generated by Django 5.0.14 on 2026-09-21 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('promotions', '0002_dailycampaign_slotreservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='daily_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='promotions.dailycampaign'),
        ),
    ]
