# Generated by Django 5.0.14 on 2026-09-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_daily_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lucky_skip_reason',
            field=models.CharField(blank=True, choices=[('REPEAT_ENTRY', "This phone number already entered that day's draw"), ('DAY_FULL', "That day's draw slots were all taken"), ('DAY_CLOSED', "The payment was confirmed after that day's draw closed"), ('HOLD_EXPIRED', 'The draw entry expired before the payment was confirmed'), ('NOT_RUNNING', 'No draw was running that day')], default='', max_length=16),
        ),
    ]
