// Static image imports (`import photo from "./x.webp"`) are typed by Next's
// image-types. Next normally references them from next-env.d.ts, but that file
// is generated by a build and gitignored -- so in CI, where the type check runs
// before any build, every image import failed with TS2307 while passing locally.
// Referencing them from a committed file removes the dependency on build order.
/// <reference types="next/image-types/global" />
