# Generated by Django 5.0.14 on 2026-09-20 15:57

import common.images
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='salons.salon')),
            ],
            options={
                'db_table': 'service_category',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_paise', models.BigIntegerField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('image', models.ImageField(blank=True, upload_to='catalog/services/', validators=[common.images.validate_image_file])),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salons.salon')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='catalog.servicecategory')),
            ],
            options={
                'db_table': 'service',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_price_paise', models.BigIntegerField()),
                ('new_price_paise', models.BigIntegerField()),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_price_changes', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.service')),
            ],
            options={
                'db_table': 'service_price_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='servicecategory',
            constraint=models.UniqueConstraint(fields=('salon', 'slug'), name='uniq_service_category_salon_slug'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['salon', 'is_active', 'display_order'], name='ix_service_salon_active_order'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('salon', 'slug'), name='uniq_service_salon_slug'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('price_paise__gte', 0)), name='ck_service_price_paise_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('duration_minutes__gte', 0)), name='ck_service_duration_minutes_non_negative'),
        ),
        migrations.AddIndex(
            model_name='servicepricehistory',
            index=models.Index(fields=['service', '-changed_at'], name='ix_price_history_service_time'),
        ),
        migrations.AddConstraint(
            model_name='servicepricehistory',
            constraint=models.CheckConstraint(check=models.Q(('old_price_paise__gte', 0), ('new_price_paise__gte', 0)), name='ck_service_price_history_non_negative'),
        ),
    ]
