# Generated by Django 5.0.14 on 2026-09-21 01:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_capacity', models.PositiveIntegerField()),
                ('lucky_count', models.PositiveIntegerField()),
                ('discount_percent', models.PositiveSmallIntegerField(default=10)),
                ('min_distinct_services', models.PositiveSmallIntegerField(default=2)),
                ('max_entries_per_phone_per_day', models.PositiveSmallIntegerField(default=1)),
                ('reward_type', models.CharField(choices=[('SERVICE_PACKAGE', 'Service package'), ('FIXED_DISCOUNT', 'Fixed discount'), ('PERCENT_DISCOUNT', 'Percent discount'), ('FIXED_CREDIT', 'Fixed credit')], default='SERVICE_PACKAGE', max_length=32)),
                ('reward_definition', models.JSONField(default=dict)),
                ('coupon_validity_days', models.PositiveSmallIntegerField(default=30)),
                ('effective_from', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_configs_created', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_configs', to='salons.salon')),
            ],
            options={
                'db_table': 'campaign_config',
                'ordering': ['-effective_from', '-created_at'],
                'indexes': [models.Index(fields=['salon', '-effective_from'], name='campaign_co_salon_i_70e7a8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='campaignconfig',
            constraint=models.CheckConstraint(check=models.Q(('daily_capacity__gt', 0)), name='ck_campaign_config_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='campaignconfig',
            constraint=models.CheckConstraint(check=models.Q(('lucky_count__lte', models.F('daily_capacity'))), name='ck_campaign_config_lucky_within_capacity'),
        ),
        migrations.AddConstraint(
            model_name='campaignconfig',
            constraint=models.CheckConstraint(check=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='ck_campaign_config_discount_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='campaignconfig',
            constraint=models.CheckConstraint(check=models.Q(('min_distinct_services__gte', 1)), name='ck_campaign_config_min_distinct_at_least_one'),
        ),
    ]
