# Generated by Django 5.0.14 on 2026-09-21 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0002_initial'),
        ('promotions', '0001_initial'),
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_date', models.DateField()),
                ('capacity', models.PositiveIntegerField()),
                ('lucky_count', models.PositiveIntegerField()),
                ('discount_percent', models.PositiveSmallIntegerField()),
                ('min_distinct_services', models.PositiveSmallIntegerField()),
                ('reward_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16)),
                ('seed_commitment', models.CharField(max_length=64)),
                ('encrypted_seed', models.TextField()),
                ('encrypted_winning_positions', models.TextField()),
                ('paid_count', models.PositiveIntegerField(default=0)),
                ('winner_count', models.PositiveIntegerField(default=0)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_campaigns', to='promotions.campaignconfig')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_campaigns', to='salons.salon')),
            ],
            options={
                'db_table': 'daily_campaign',
                'ordering': ['-campaign_date'],
            },
        ),
        migrations.CreateModel(
            name='SlotReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONSUMED', 'Consumed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slot_reservations', to='customers.customer')),
                ('daily_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='promotions.dailycampaign')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_reservation', to='orders.order')),
            ],
            options={
                'db_table': 'slot_reservation',
            },
        ),
        migrations.AddConstraint(
            model_name='dailycampaign',
            constraint=models.UniqueConstraint(fields=('salon', 'campaign_date'), name='uniq_daily_campaign_salon_date'),
        ),
        migrations.AddConstraint(
            model_name='dailycampaign',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gt', 0)), name='ck_daily_campaign_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='dailycampaign',
            constraint=models.CheckConstraint(check=models.Q(('lucky_count__lte', models.F('capacity'))), name='ck_daily_campaign_lucky_within_capacity'),
        ),
        migrations.AddConstraint(
            model_name='dailycampaign',
            constraint=models.CheckConstraint(check=models.Q(('paid_count__lte', models.F('capacity'))), name='ck_daily_campaign_paid_within_capacity'),
        ),
        migrations.AddConstraint(
            model_name='dailycampaign',
            constraint=models.CheckConstraint(check=models.Q(('winner_count__lte', models.F('lucky_count'))), name='ck_daily_campaign_winners_within_lucky_count'),
        ),
        migrations.AddIndex(
            model_name='slotreservation',
            index=models.Index(condition=models.Q(('status', 'ACTIVE')), fields=['daily_campaign'], name='ix_slot_reservation_active'),
        ),
        migrations.AddIndex(
            model_name='slotreservation',
            index=models.Index(fields=['status', 'expires_at'], name='slot_reserv_status_e45361_idx'),
        ),
    ]
