# Generated by Django 5.0.14 on 2026-09-21 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_lucky_skip_reason'),
        ('promotions', '0002_dailycampaign_slotreservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuckyDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_number', models.PositiveIntegerField()),
                ('is_winner', models.BooleanField()),
                ('reward_refund_paise', models.BigIntegerField(default=0)),
                ('free_services', models.JSONField(blank=True, default=list)),
                ('decided_at', models.DateTimeField()),
                ('daily_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='promotions.dailycampaign')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lucky_decision', to='orders.order')),
            ],
            options={
                'db_table': 'lucky_decision',
                'ordering': ['daily_campaign', 'participant_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='luckydecision',
            constraint=models.UniqueConstraint(fields=('daily_campaign', 'participant_number'), name='uniq_lucky_decision_participant'),
        ),
        migrations.AddConstraint(
            model_name='luckydecision',
            constraint=models.CheckConstraint(check=models.Q(('participant_number__gte', 1)), name='ck_lucky_decision_participant_positive'),
        ),
        migrations.AddConstraint(
            model_name='luckydecision',
            constraint=models.CheckConstraint(check=models.Q(('reward_refund_paise__gte', 0)), name='ck_lucky_decision_refund_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='luckydecision',
            constraint=models.CheckConstraint(check=models.Q(('is_winner', True), ('reward_refund_paise', 0), _connector='OR'), name='ck_lucky_decision_refund_only_for_winners'),
        ),
    ]
