# Generated by Django 5.0.14 on 2026-09-21 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_lucky_skip_reason'),
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_image', models.BinaryField(blank=True, null=True)),
                ('qr_content_type', models.CharField(blank=True, max_length=32)),
                ('qr_sha256', models.CharField(blank=True, max_length=64)),
                ('qr_width', models.PositiveIntegerField(blank=True, null=True)),
                ('qr_height', models.PositiveIntegerField(blank=True, null=True)),
                ('qr_updated_at', models.DateTimeField(blank=True, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('payee_name', models.CharField(blank=True, max_length=100)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='salons.salon')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_settings',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('MANUAL_UPI', 'UPI QR (confirmed by the salon)')], max_length=24)),
                ('status', models.CharField(choices=[('AWAITING_CONFIRMATION', 'Awaiting confirmation'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='AWAITING_CONFIRMATION', max_length=24)),
                ('amount_paise', models.BigIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('reference', models.CharField(max_length=64)),
                ('submitted_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_decided', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='salons.salon')),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='payment_status_27ae47_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount_paise__gte', 0)), name='ck_payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('AWAITING_CONFIRMATION', 'CONFIRMED'))), fields=('provider', 'reference'), name='uniq_payment_live_reference'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('AWAITING_CONFIRMATION', 'CONFIRMED'))), fields=('order',), name='uniq_payment_one_live_per_order'),
        ),
    ]
