# Generated by Django 5.0.14 on 2026-09-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
