# Generated by Django 5.0.14 on 2026-09-21 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_lucky_skip_reason'),
        ('payments', '0001_initial'),
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('LUCKY_REWARD', 'Lucky slot reward')], max_length=24)),
                ('amount_paise', models.BigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'To be sent'), ('SENT', 'Sent')], default='PENDING', max_length=16)),
                ('method', models.CharField(blank=True, choices=[('UPI', 'UPI transfer'), ('CASH', 'Cash at the salon')], max_length=8)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='salons.salon')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refund',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='refund_status_63f8eb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(check=models.Q(('amount_paise__gt', 0)), name='ck_refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(fields=('order', 'reason'), name='uniq_refund_order_reason'),
        ),
    ]
